import { apiGet, apiPost, apiPut, apiDelete } from '../../api'
export const listTrips     = (status) => apiGet('/trips' + (status ? `?status=${status}` : ''))
export const startTrip     = (body)   => apiPost('/trips', null, body)
export const endTrip       = (id, body) => apiPost(`/trips/${id}/end`, null, body)
export const saveChecklist = (id, body) => apiPut(`/trips/${id}/checklist`, null, body)
export const listCatchLogs    = (tripId)              => apiGet(`/trips/${tripId}/catches`)
export const createCatchLog   = (tripId, body)        => apiPost(`/trips/${tripId}/catches`, null, body)
export const updateCatchLog   = (tripId, logId, body) => apiPut(`/trips/${tripId}/catches/${logId}`, null, body)
export const deleteCatchLog   = (tripId, logId)       => apiDelete(`/trips/${tripId}/catches/${logId}`)
export const settleCatchLog   = (tripId, logId, body) => apiPost(`/trips/${tripId}/catches/${logId}/settle`, null, body)
export const getTrip          = (id)                  => apiGet(`/trips/${id}`)
