# Generated by Django 6.0.1 on 2026-04-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_max_score', models.IntegerField(default=2)),
                ('caution_max_score', models.IntegerField(default=5)),
                ('gust_threshold_kmh', models.FloatField(default=60.0)),
                ('heavy_rain_mm_h', models.FloatField(default=10.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conditions_riskconfig',
            },
        ),
        migrations.CreateModel(
            name='RiskThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('WAVE', 'Wave Height'), ('WIND', 'Wind Speed')], max_length=10)),
                ('upper_bound', models.FloatField(help_text="Upper bound for this tier. Use 9999.0 for 'infinity'.")),
                ('score_points', models.IntegerField(help_text='Points added when value <= upper_bound.')),
                ('order', models.IntegerField(help_text='Evaluation order (ascending).')),
            ],
            options={
                'db_table': 'conditions_riskthreshold',
                'ordering': ['parameter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FishingZone',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('region', models.CharField(default='La Union', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'conditions_fishingzone',
                'indexes': [models.Index(fields=['is_active'], name='conditions__is_acti_7fa7e4_idx')],
            },
        ),
    ]
